# Generated by Django 5.0.6 on 2024-09-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_name', models.CharField(max_length=122)),
                ('date_disaster', models.CharField(max_length=122)),
                ('dead', models.CharField(max_length=1299)),
                ('injured', models.CharField(max_length=122)),
                ('heading', models.CharField(max_length=1220)),
                ('description', models.CharField(max_length=12000)),
                ('category', models.CharField(max_length=122)),
            ],
        ),
    ]
