# Generated by Django 5.0.6 on 2024-09-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_heading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heading',
        ),
    ]
